// Usar para verificar um ERRO no codigo;

try{
    console.log(naoExisto)
}catch(err){
    console.log("Erro")
    console.log(err);
}